version: '3.8'

services:
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - SERVICE_ACCOUNT_ID=${SERVICE_ACCOUNT_ID}
      - KEY_ID=${KEY_ID}
      - FOLDER_ID=${FOLDER_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - ORCHESTRATOR_PORT=8000
      - FORCE_REBUILD_INDEX=${FORCE_REBUILD_INDEX:-false}
    volumes:
      - ./orchestrator:/app
      - vectorstore_data:/app/vectorstore
      - logs_data:/app/logs
    restart: unless-stopped

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile.bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ORCHESTRATOR_URL=http://orchestrator:8000
    depends_on:
      - orchestrator
    restart: unless-stopped

volumes:
  vectorstore_data:
  logs_data: