
services:
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile.api
    ports:
      - "8001:8000"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - SERVICE_ACCOUNT_ID=${SERVICE_ACCOUNT_ID}
      - KEY_ID=${KEY_ID}
      - FOLDER_ID=${FOLDER_ID}
      - PRIVATE_KEY_PATH=/app/secrets/private_key.pem
      - ORCHESTRATOR_PORT=8000
      - FORCE_REBUILD_INDEX=${FORCE_REBUILD_INDEX:-false}
      - YAND_EMBEDDING_MODEL_URI=${YAND_EMBEDDING_MODEL_URI}
      - YAND_TEXT_MODEL_URI=${YAND_TEXT_MODEL_URI}
    volumes:
      - ./orchestrator:/app
      - ./secrets:/app/secrets:ro
      - vectorstore_data:/app/vectorstore
      - logs_data:/app/logs
      - ./faiss_index_yandex:/app/faiss_index_yandex
    restart: unless-stopped

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile.bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ORCHESTRATOR_URL=http://orchestrator:8000
      - YAND_EMBEDDING_MODEL_URI=${YAND_EMBEDDING_MODEL_URI}
      - YAND_TEXT_MODEL_URI=${YAND_TEXT_MODEL_URI}
    depends_on:
      - orchestrator
    restart: unless-stopped

volumes:
  vectorstore_data:
  logs_data:
