global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ai-bartender-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
