FROM python:3.11-slim

WORKDIR /app

# Копируем зависимости бота
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код бота
COPY . .

EXPOSE 8080

CMD ["python", "tg_bot.py"]